### PR TITLE
fix error message in test_convergence without analytical solution

### LINKED ISSUE #98: Throw nice error when running convergence test without analytical solution
Reported by a colleague who is not on GitHub yet:

```julia
using OrdinaryDiffEq, DiffEqDevTools

f_analytic(u0,p,t) = u0*exp(t)
ff = ODEFunction((u, p, t) -> u, analytic=f_analytic)
prob1 = ODEProblem(ff, 1.0, (0.0, 5.0))

prob2 = ODEProblem((u, p, t) -> u, 1.0, (0.0, 5.0))

dts = (1 / 2) .^ (7:-1:4)

sim1 = test_convergence(dts, prob1, DP5()) #fine
sim2 = test_convergence(dts, prob2, DP5()) #error
```

This yields

```julia-repl
julia> sim2 = test_convergence(dts, prob2, DP5()) #error
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:872
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at range.jl:872
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at dict.jl:712
  ...
Stacktrace:
 [1] isempty(itr::Nothing)
   @ Base ./essentials.jl:788
 [2] ConvergenceSimulation(solutions::Vector{ODESolution{Float64, 1, Vector{Float64}, Nothing, Nothing, Vector{Float64}, Vector{Vector{Float64}}, ODEProblem{Float64, Tuple{Float64, Float64}, false, SciMLBase.NullParameters, ODEFunction{false, SciMLBase.AutoSpecialize, var"#3#4", LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, DP5, OrdinaryDiffEq.InterpolationData{ODEFunction{false, SciMLBase.AutoSpecialize, var"#3#4", LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Vector{Float64}, Vector{Float64}, Vector{Vector{Float64}}, OrdinaryDiffEq.DP5ConstantCache{Float64, Float64}}, DiffEqBase.DEStats}}, convergence_axis::Vector{Float64}; auxdata::Dict{Symbol, Vector{Float64}}, additional_errors::Nothing, expected_value::Nothing)
   @ DiffEqDevTools ~/.julia/packages/DiffEqDevTools/sfX7w/src/convergence.jl:17
 [3] test_convergence(dts::Vector{Float64}, prob::ODEProblem{Float64, Tuple{Float64, Float64}, false, SciMLBase.NullParameters, ODEFunction{false, SciMLBase.AutoSpecialize, var"#3#4", LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, alg::DP5; save_everystep::Bool, adaptive::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ DiffEqDevTools ~/.julia/packages/DiffEqDevTools/sfX7w/src/convergence.jl:207
 [4] test_convergence(dts::Vector{Float64}, prob::ODEProblem{Float64, Tuple{Float64, Float64}, false, SciMLBase.NullParameters, ODEFunction{false, SciMLBase.AutoSpecialize, var"#3#4", LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, alg::DP5)
   @ DiffEqDevTools ~/.julia/packages/DiffEqDevTools/sfX7w/src/convergence.jl:200
 [5] top-level scope
   @ REPL[10]:1
```

It would be nice to throw a good error message in this case.

### PR DESCRIPTION
**Pull request by SKopecz**
This is a fix for issue #98. This is my 1st PR to SciML, please help me improve it, if necessary.
Closes #98.

### CODE REVIEW

**Review by ranocha — APPROVED** [review]
LGTM! It would be good to get a review from someone more involved in the internals to understand why this fix was necessary. Did the type of `solutions[1].errors` change at some point in the past when no analytical solution is provided?

**Comment by ranocha** [comment]
@ChrisRackauckas Would it make sense to add this repo to the DiffEq team? I can't approve the workflow for this PR, for example.

**Comment by ChrisRackauckas** [comment]
yes it would

File: test/analyticless_convergence_tests.jl [hunk 1]
```diff
@@ -14,6 +14,8 @@ test_setup = Dict(:alg => Vern9(), :reltol => 1e-25, :abstol => 1e-25)
 sim1 = analyticless_test_convergence(dts, prob, Tsit5(), test_setup)
 sim2 = analyticless_test_convergence(dts, prob, Vern9(), test_setup)
 
+@test_throws "No analytical solution set." test_convergence(dts, prob, Tsit5())
```
Comment (ranocha) [inline test/analyticless_convergence_tests.jl:17]:
```suggestion
if VERSION >= v"1.8"
  @test_throws "No analytical solution set." test_convergence(dts, prob, Tsit5())
end
```
Ci on Julia v1.6 fails since the `@test_throws` macro has only been extended to string arguments in Julia v1.8. Thus, we need to use this test only on Julia v1.8 and newer.

**Review by ranocha — APPROVED** [review]

**Comment by ranocha** [comment]
Someone needs to approve running CI again (or add this repo to the DiffEq team to let me do this).

**Review by ranocha — APPROVED** [review]

**Comment by ranocha** [comment]
LGTM. The Codecov failure seems spurious.

**Comment by ChrisRackauckas** [comment]
It is. And you should have the access for this repo now. I think it didn't post because I lost wifi 😓
